#!/usr/bin/env python3
"""
Generate test configuration files for MeshCraft workflow tests.

This script scans the workflows/ directory and creates YAML configuration
files for different test profiles (quick, full, ci).
"""

import argparse
import yaml
from pathlib import Path
from typing import Dict, List, Any

# Add utils to path
import sys
sys.path.insert(0, str(Path(__file__).parent))

from testutils import (
    convert_workflow_file,
    detect_workflow_model_type,
    get_trellis_attention_configs,
    get_hunyuan_attention_configs,
)


def discover_workflows(workflow_dir: Path) -> Dict[str, Dict[str, Any]]:
    """
    Discover all workflows in the workflow directory.

    Args:
        workflow_dir: Path to workflows directory

    Returns:
        Dict mapping workflow names to their metadata
    """
    if not workflow_dir.exists():
        raise FileNotFoundError(f"Workflow directory not found: {workflow_dir}")

    workflows = {}

    for json_file in workflow_dir.glob("*.json"):
        workflow_name = json_file.stem

        try:
            # Convert and detect model type
            workflow_dict = convert_workflow_file(str(json_file))
            model_type = detect_workflow_model_type(workflow_dict)

            if model_type == "unknown":
                print(f"⚠️  Skipping {workflow_name}: unknown model type")
                continue

            workflows[workflow_name] = {
                "path": json_file,
                "model_type": model_type,
            }
            print(f"✅ Found workflow: {workflow_name} (model: {model_type})")

        except Exception as e:
            print(f"❌ Error processing {workflow_name}: {e}")

    return workflows


def generate_full_config(workflows: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Generate full test configuration (all workflows, all attention configs)."""
    config = {
        "# ComfyUI-MeshCraft Test Configuration": None,
        "# Profile": "full - Run all workflows with all attention configurations",
        "# Generated by": "tests/generate_config.py",
    }

    # Workflow settings
    workflow_settings = {}
    for workflow_name, workflow_data in workflows.items():
        # Set longer timeout for text-to-mesh
        timeout = 900 if "t2m" in workflow_name else 600

        workflow_settings[workflow_name] = {
            "enabled": True,
            "timeout": timeout,
            "model_type": workflow_data["model_type"],
        }

    config["workflows"] = workflow_settings

    # Test specifications (use all configs)
    tests = {}
    for workflow_name in workflows.keys():
        tests[workflow_name] = "all"

    config["tests"] = tests

    return config


def generate_quick_config(workflows: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Generate quick test configuration (subset of workflows and attention configs)."""
    config = {
        "# ComfyUI-MeshCraft Test Configuration": None,
        "# Profile": "quick - Fast test suite for rapid iteration (1-2 configs per workflow)",
        "# Generated by": "tests/generate_config.py",
    }

    # Workflow settings (only enable i2m workflows for quick testing)
    workflow_settings = {}
    for workflow_name, workflow_data in workflows.items():
        # Only enable image-to-mesh workflows in quick mode
        enabled = "i2m" in workflow_name
        timeout = 600

        workflow_settings[workflow_name] = {
            "enabled": enabled,
            "timeout": timeout,
            "model_type": workflow_data["model_type"],
        }

    config["workflows"] = workflow_settings

    # Test specifications (use subset of configs)
    tests = {}
    for workflow_name, workflow_data in workflows.items():
        model_type = workflow_data["model_type"]

        if model_type == "trellis":
            # Just test flash-attn and sdpa with auto spconv
            tests[workflow_name] = [
                "trellis-flash-attn-auto",
                "trellis-sdpa-auto",
            ]
        elif model_type == "hunyuan":
            # Just test sdpa
            tests[workflow_name] = [
                "hunyuan-sdpa",
            ]

    config["tests"] = tests

    return config


def generate_ci_config(workflows: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Generate CI test configuration (balanced coverage for continuous integration)."""
    config = {
        "# ComfyUI-MeshCraft Test Configuration": None,
        "# Profile": "ci - Balanced test suite for continuous integration",
        "# Generated by": "tests/generate_config.py",
    }

    # Workflow settings (enable all workflows)
    workflow_settings = {}
    for workflow_name, workflow_data in workflows.items():
        timeout = 900 if "t2m" in workflow_name else 600

        workflow_settings[workflow_name] = {
            "enabled": True,
            "timeout": timeout,
            "model_type": workflow_data["model_type"],
        }

    config["workflows"] = workflow_settings

    # Test specifications (balanced subset)
    tests = {}
    for workflow_name, workflow_data in workflows.items():
        model_type = workflow_data["model_type"]

        if model_type == "trellis":
            # Test flash-attn, sdpa, and xformers with different spconv algos
            tests[workflow_name] = [
                "trellis-flash-attn-auto",
                "trellis-sdpa-flash-native",
                "trellis-xformers-auto",
            ]
        elif model_type == "hunyuan":
            # Test both attention modes
            tests[workflow_name] = "all"

    config["tests"] = tests

    return config


def save_config(config: Dict[str, Any], output_path: Path):
    """Save configuration to YAML file."""
    # Remove comment keys (used for YAML header comments)
    filtered_config = {
        k: v for k, v in config.items()
        if not k.startswith("#")
    }

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        # Write header comments
        for key, value in config.items():
            if key.startswith("#"):
                f.write(f"{key}: {value}\n" if value else f"{key}\n")

        f.write("\n")

        # Write YAML content
        yaml.dump(
            filtered_config,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    print(f"✅ Generated: {output_path}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate test configuration files for MeshCraft workflow tests"
    )
    parser.add_argument(
        "--workflow-dir",
        type=Path,
        default=None,
        help="Directory containing workflow JSON files (default: ../workflows)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for config files (default: configs/)",
    )
    parser.add_argument(
        "--profile",
        choices=["quick", "full", "ci", "all"],
        default="all",
        help="Which profile(s) to generate (default: all)",
    )

    args = parser.parse_args()

    # Determine paths
    script_dir = Path(__file__).parent
    workflow_dir = args.workflow_dir or (script_dir.parent / "workflows")
    output_dir = args.output_dir or (script_dir / "configs")

    print(f"Scanning workflows in: {workflow_dir}")
    print(f"Output directory: {output_dir}")
    print()

    # Discover workflows
    workflows = discover_workflows(workflow_dir)

    if not workflows:
        print("❌ No workflows found!")
        return 1

    print(f"\nFound {len(workflows)} workflow(s)")
    print()

    # Generate configurations
    profiles_to_generate = ["full"] if args.profile == "all" else [args.profile]

    for profile in profiles_to_generate:
        if profile == "quick":
            config = generate_quick_config(workflows)
            output_path = output_dir / "quick.yaml"
        elif profile == "full":
            config = generate_full_config(workflows)
            output_path = output_dir / "default.yaml"  # Full is the default
        elif profile == "ci":
            config = generate_ci_config(workflows)
            output_path = output_dir / "ci.yaml"

        save_config(config, output_path)

    print(f"\n🎉 Done! Generated {len(profiles_to_generate)} config file(s)")
    print("\nUsage:")
    print("  # Use default (full) config:")
    print("  ./run_tests.sh test_workflows.py -v")
    print("\n  # Generate and use other profiles:")
    print("  python generate_config.py --profile=quick")
    print("  ./run_tests.sh test_workflows.py --config=configs/quick.yaml -v")

    return 0


if __name__ == "__main__":
    sys.exit(main())
