"""
ComfyUI-MeshCraft Nodes

All node definitions organized in one place.
"""

from .mesh_nodes import NODE_CLASS_MAPPINGS as MESH_NODES, NODE_DISPLAY_NAME_MAPPINGS as MESH_DISPLAY
from .interpolation_nodes import NODE_CLASS_MAPPINGS as INTERP_NODES, NODE_DISPLAY_NAME_MAPPINGS as INTERP_DISPLAY
from .hunyuan_nodes import NODE_CLASS_MAPPINGS as HUNYUAN_NODES, NODE_DISPLAY_NAME_MAPPINGS as HUNYUAN_DISPLAY
from .andrea_nodes import NODE_CLASS_MAPPINGS as ANDREA_NODES, NODE_DISPLAY_NAME_MAPPINGS as ANDREA_DISPLAY
from .rendering_nodes import NODE_CLASS_MAPPINGS as RENDERING_NODES, NODE_DISPLAY_NAME_MAPPINGS as RENDERING_DISPLAY
from .trellis_nodes import NODE_CLASS_MAPPINGS as TRELLIS_NODES, NODE_DISPLAY_NAME_MAPPINGS as TRELLIS_DISPLAY

__all__ = [
    "MESH_NODES",
    "MESH_DISPLAY",
    "INTERP_NODES",
    "INTERP_DISPLAY",
    "HUNYUAN_NODES",
    "HUNYUAN_DISPLAY",
    "ANDREA_NODES",
    "ANDREA_DISPLAY",
    "RENDERING_NODES",
    "RENDERING_DISPLAY",
    "TRELLIS_NODES",
    "TRELLIS_DISPLAY",
]
